### PR TITLE
early error out if given ip is already allocated, closes #47

### LINKED ISSUE #47: AcquireSpecificIP will block forever if IPv6 is already taken
Hey everyone!
I am playing around with this library in my IPAM controller for Kubernetes https://github.com/routerd/kube-ipam.

Today I stumbled across a strange Bug.
When a specific IPv6 address is already allocated `AcquireSpecificIP` will block forever...
(or at least longer than I am patient for :D -> 5min+ )

Hope I am not just grossly misusing this library :)

Tested on `v1.8.1` according to `go.mod`
```
$ go version
go version go1.15.8 linux/amd64
```

Here is a little go-snippet that I have used to reproduce the issue:
```go
const (
	cidr = "fd9c:fd74:6b8d:1020::/64"
)

func main() {
	ipam := goipam.New()
	ipam.NewPrefix(cidr)

	ip1, err := ipam.AcquireSpecificIP(cidr, "fd9c:fd74:6b8d:1020::1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip1)

	ip2, err := ipam.AcquireSpecificIP(cidr, "fd9c:fd74:6b8d:1020::1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip2)
}
```

will return:
```
$ go run ./ipv6/main.go 
got static:  &{fd9c:fd74:6b8d:1020::1 fd9c:fd74:6b8d:1020::/64}
< blocks forever >
```

The same code using IPv4 is working fine:
```go
const (
	cidr = "172.20.0.0/24"
)

func main() {
	ipam := goipam.New()
	ipam.NewPrefix(cidr)

	ip1, err := ipam.AcquireSpecificIP(cidr, "172.20.0.1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip1)

	ip2, err := ipam.AcquireSpecificIP(cidr, "172.20.0.1")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("got static: ", ip2)
}
```
```
$ go run ./ipv4/main.go
got static:  &{172.20.0.1 172.20.0.0/24}
NoIPAvailableError: no more ips in prefix: 172.20.0.0/24 left, length of prefix.ips: 3
exit status 1
```

### PR DESCRIPTION
**Pull request by majst01**

### CODE REVIEW

File: prefix.go [hunk 1]
```diff
@@ -318,6 +318,10 @@ func (i *ipamer) acquireSpecificIPInternal(prefixCidr, specificIP string) (*IP,
 		if !ipnet.Contains(specificIPnet) {
 			return nil, fmt.Errorf("given ip:%s is not in %s", specificIP, prefixCidr)
 		}
+		_, ok := prefix.ips[specificIPnet.String()]
+		if ok {
+			return nil, fmt.Errorf("given ip:%s is already allocated", specificIP)
```
Comment (thetechnick) [inline prefix.go:323]: Cool stuff!
Would you mind wrapping something like `ErrAlreadyAllocated` here,
so I can `errors.Is(err, goipam.ErrAlreadyAllocated)` when I use this function?

Obviously not part of this PR, but if I could wish for something :)
It would be awesome if callers could distinguish between 3 error states:
- transient errors (due to optimistic locking?)
- non transient/validation errors (stuff that will never work, like trying to allocate an IP not in the CIDR)
- already allocated IPs (So I can either retry later in the hope it is free or actually wait for a lease of the specific IP to expire)

Caller code relying on `goipam.ErrNoIPAvailable` being returned in this case:
https://github.com/routerd/kube-ipam/blob/separate-ipfamilies/internal/controllers/iplease_controller.go#L148

**Review by thetechnick — CHANGES_REQUESTED** [review]

File: prefix.go (hunk 1 above)
Comment (majst01) [reply prefix.go]: good point, done for this case.

**Comment by erdii** [comment]
you are amazing! i'm going to close my pr over this!

**Review by thetechnick — APPROVED** [review]
:100:

**Review by droid42 — APPROVED** [review]
LGTM
